
class Constants {   
    static get Actions() {
        return {
            SetSelectedLang: "SetSelectedLang"
        };
    }
    
    static get APIUrl() {
        return {
            base: "http://localhost:4000/api/",
            langService: "langService/"
        };
    }
    
    static get LanguageCodes() {
        const languageCodes = [
            {code:"af-ZA", desc:"Afrikaans (South Africa)"},
            {code:"ar-AE", desc:"Arabic (U.A.E.)"},
            {code:"ar-BH", desc:"Arabic (Bahrain)"},
            {code:"ar-DZ", desc:"Arabic (Algeria)"},
            {code:"ar-EG", desc:"Arabic (Egypt)"},
            {code:"ar-IQ", desc:"Arabic (Iraq)"},
            {code:"ar-JO", desc:"Arabic (Jordan)"},
            {code:"ar-KW", desc:"Arabic (Kuwait)"},
            {code:"ar-LB", desc:"Arabic (Lebanon)"},
            {code:"ar-LY", desc:"Arabic (Libya)"},
            {code:"ar-MA", desc:"Arabic (Morocco)"},
            {code:"ar-OM", desc:"Arabic (Oman)"},
            {code:"ar-QA", desc:"Arabic (Qatar)"},
            {code:"ar-SA", desc:"Arabic (Saudi Arabia)"},
            {code:"ar-SY", desc:"Arabic (Syria)"},
            {code:"ar-TN", desc:"Arabic (Tunisia)"},
            {code:"ar-YE", desc:"Arabic (Yemen)"},
            {code:"az-AZ", desc:"Azeri (Azerbaijan)"},
            {code:"be-BY", desc:"Belarusian (Belarus)"},
            {code:"bg-BG", desc:"Bulgarian (Bulgaria)"},
            {code:"bs-BA", desc:"Bosnian (Bosnia and Herzegovina)"},
            {code:"ca-ES", desc:"Catalan (Spain)"},
            {code:"cs-CZ", desc:"Czech (Czech Republic)"},
            {code:"cy-GB", desc:"Welsh (United Kingdom)"},
            {code:"da-DK", desc:"Danish (Denmark)"},
            {code:"de-AT", desc:"German (Austria)"},
            {code:"de-CH", desc:"German (Switzerland)"},
            {code:"de-DE", desc:"German (Germany)"},
            {code:"de-LI", desc:"German (Liechtenstein)"},
            {code:"de-LU", desc:"German (Luxembourg)"},
            {code:"dv-MV", desc:"Divehi (Maldives)"},
            {code:"el-GR", desc:"Greek (Greece)"},
            {code:"en-AU", desc:"English (Australia)"},
            {code:"en-BZ", desc:"English (Belize)"},
            {code:"en-CA", desc:"English (Canada)"},
            {code:"en-CB", desc:"English (Caribbean)"},
            {code:"en-GB", desc:"English (United Kingdom)"},
            {code:"en-IE", desc:"English (Ireland)"},
            {code:"en-JM", desc:"English (Jamaica)"},
            {code:"en-NZ", desc:"English (New Zealand)"},
            {code:"en-PH", desc:"English (Republic of the Philippines)"},
            {code:"en-TT", desc:"English (Trinidad and Tobago)"},
            {code:"en-US", desc:"English (United States)"},
            {code:"en-ZA", desc:"English (South Africa)"},
            {code:"en-ZW", desc:"English (Zimbabwe)"},
            {code:"es-AR", desc:"Spanish (Argentina)"},
            {code:"es-BO", desc:"Spanish (Bolivia)"},
            {code:"es-CL", desc:"Spanish (Chile)"},
            {code:"es-CO", desc:"Spanish (Colombia)"},
            {code:"es-CR", desc:"Spanish (Costa Rica)"},
            {code:"es-DO", desc:"Spanish (Dominican Republic)"},
            {code:"es-EC", desc:"Spanish (Ecuador)"},
            {code:"es-ES", desc:"Spanish (Spain)"},
            {code:"es-GT", desc:"Spanish (Guatemala)"},
            {code:"es-HN", desc:"Spanish (Honduras)"},
            {code:"es-MX", desc:"Spanish (Mexico)"},
            {code:"es-NI", desc:"Spanish (Nicaragua)"},
            {code:"es-PA", desc:"Spanish (Panama)"},
            {code:"es-PE", desc:"Spanish (Peru)"},
            {code:"es-PR", desc:"Spanish (Puerto Rico)"},
            {code:"es-PY", desc:"Spanish (Paraguay)"},
            {code:"es-SV", desc:"Spanish (El Salvador)"},
            {code:"es-UY", desc:"Spanish (Uruguay)"},
            {code:"es-VE", desc:"Spanish (Venezuela)"},
            {code:"et-EE", desc:"Estonian (Estonia)"},
            {code:"eu-ES", desc:"Basque (Spain)"},
            {code:"fa-IR", desc:"Farsi (Iran)"},
            {code:"fi-FI", desc:"Finnish (Finland)"},
            {code:"fo-FO", desc:"Faroese (Faroe Islands)"},
            {code:"fr-BE", desc:"French (Belgium)"},
            {code:"fr-CA", desc:"French (Canada)"},
            {code:"fr-CH", desc:"French (Switzerland)"},
            {code:"fr-FR", desc:"French (France)"},
            {code:"fr-LU", desc:"French (Luxembourg)"},
            {code:"fr-MC", desc:"French (Principality of Monaco)"},
            {code:"gl-ES", desc:"Galician (Spain)"},
            {code:"gu-IN", desc:"Gujarati (India)"},
            {code:"he-IL", desc:"Hebrew (Israel)"},
            {code:"hi-IN", desc:"Hindi (India)"},
            {code:"hr-BA", desc:"Croatian (Bosnia and Herzegovina)"},
            {code:"hr-HR", desc:"Croatian (Croatia)"},
            {code:"hu-HU", desc:"Hungarian (Hungary)"},
            {code:"hy-AM", desc:"Armenian (Armenia)"},
            {code:"id-ID", desc:"Indonesian (Indonesia)"},
            {code:"is-IS", desc:"Icelandic (Iceland)"},
            {code:"it-CH", desc:"Italian (Switzerland)"},
            {code:"it-IT", desc:"Italian (Italy)"},
            {code:"ja-JP", desc:"Japanese (Japan)"},
            {code:"ka-GE", desc:"Georgian (Georgia)"},
            {code:"kk-KZ", desc:"Kazakh (Kazakhstan)"},
            {code:"kn-IN", desc:"Kannada (India)"},
            {code:"ko-KR", desc:"Korean (Korea)"},
            {code:"kok-IN", desc:"Konkani (India)"},
            {code:"ky-KG", desc:"Kyrgyz (Kyrgyzstan)"},
            {code:"lt-LT", desc:"Lithuanian (Lithuania)"},
            {code:"lv-LV", desc:"Latvian (Latvia)"},
            {code:"mi-NZ", desc:"Maori (New Zealand)"},
            {code:"mk-MK", desc:"FYRO Macedonian (Former Yugoslav Republic of Macedonia)"},
            {code:"mn-MN", desc:"Mongolian (Mongolia)"},
            {code:"mr-IN", desc:"Marathi (India)"},
            {code:"ms-BN", desc:"Malay (Brunei Darussalam)"},
            {code:"ms-MY", desc:"Malay (Malaysia)"},
            {code:"mt-MT", desc:"Maltese (Malta)"},
            {code:"nb-NO", desc:"Norwegian (Norway)"},
            {code:"nl-BE", desc:"Dutch (Belgium)"},
            {code:"nl-NL", desc:"Dutch (Netherlands)"},
            {code:"ns-ZA", desc:"Northern Sotho (South Africa)"},
            {code:"pa-IN", desc:"Punjabi (India)"},
            {code:"pl-PL", desc:"Polish (Poland)"},
            {code:"ps-AR", desc:"Pashto (Afghanistan)"},
            {code:"pt-BR", desc:"Portuguese (Brazil)"},
            {code:"pt-PT", desc:"Portuguese (Portugal)"},
            {code:"qu-BO", desc:"Quechua (Bolivia)"},
            {code:"qu-EC", desc:"Quechua (Ecuador)"},
            {code:"qu-PE", desc:"Quechua (Peru)"},
            {code:"ro-RO", desc:"Romanian (Romania)"},
            {code:"ru-RU", desc:"Russian (Russia)"},
            {code:"sa-IN", desc:"Sanskrit (India)"},
            {code:"se-FI", desc:"Sami (Finland)"},
            {code:"se-NO", desc:"Sami (Norway)"},
            {code:"se-SE", desc:"Sami (Sweden)"},
            {code:"sk-SK", desc:"Slovak (Slovakia)"},
            {code:"sl-SI", desc:"Slovenian (Slovenia)"},
            {code:"sq-AL", desc:"Albanian (Albania)"},
            {code:"sr-BA", desc:"Serbian (Bosnia and Herzegovina)"},
            {code:"sr-SP", desc:"Serbian (Serbia and Montenegro)"},
            {code:"sv-FI", desc:"Swedish (Finland)"},
            {code:"sv-SE", desc:"Swedish (Sweden)"},
            {code:"sw-KE", desc:"Swahili (Kenya)"},
            {code:"syr-SY", desc:"Syriac (Syria)"},
            {code:"ta-IN", desc:"Tamil (India)"},
            {code:"te-IN", desc:"Telugu (India)"},
            {code:"th-TH", desc:"Thai (Thailand)"},
            {code:"tl-PH", desc:"Tagalog (Philippines)"},
            {code:"tn-ZA", desc:"Tswana (South Africa)"},
            {code:"tr-TR", desc:"Turkish (Turkey)"},
            {code:"tt-RU", desc:"Tatar (Russia)"},
            {code:"uk-UA", desc:"Ukrainian (Ukraine)"},
            {code:"ur-PK", desc:"Urdu (Islamic Republic of Pakistan)"},
            {code:"uz-UZ", desc:"Uzbek (Uzbekistan)"},
            {code:"vi-VN", desc:"Vietnamese (Viet Nam)"},
            {code:"xh-ZA", desc:"Xhosa (South Africa)"},
            {code:"zh-CN", desc:"Chinese (China)"},
            {code:"zh-HK", desc:"Chinese (Hong Kong)"},
            {code:"zh-MO", desc:"Chinese (Macau)"},
            {code:"zh-SG", desc:"Chinese (Singapore)"},
            {code:"zh-TW", desc:"Chinese (Taiwan)"},
            {code:"zu-ZA", desc:"Zulu (South Africa)"}
        ];
        return languageCodes;
    }
}

export default Constants;